# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Importer < Formula
  desc "Import any lines, from anywhere"
  homepage "https://github.com/upsidr/importer"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/upsidr/importer/releases/download/v0.1.4/importer_0.1.4_darwin_arm64.tar.gz"
      sha256 "42aeb607f5ac941377792c719f4c5885b4b442576558fc6e162f834085fde2ab"

      def install
        bin.install "importer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/upsidr/importer/releases/download/v0.1.4/importer_0.1.4_darwin_amd64.tar.gz"
      sha256 "92a11df2ad613328a3a32e6183e4bb1d0356b9c0685a16be2ec53aba23332e1b"

      def install
        bin.install "importer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/upsidr/importer/releases/download/v0.1.4/importer_0.1.4_linux_amd64.tar.gz"
      sha256 "30c426cb826d0478d27993b2dc2729a3886b553b3b950547b88aa053524bf6b9"

      def install
        bin.install "importer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/upsidr/importer/releases/download/v0.1.4/importer_0.1.4_linux_arm64.tar.gz"
      sha256 "d371fe3afee59e25efe5ce24c30a52088d72da1ffee3a256e83d882c6c57530f"

      def install
        bin.install "importer"
      end
    end
  end
end
