# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Importer < Formula
  desc "Import lines from anywhere"
  homepage "https://github.com/upsidr/importer"
  version "0.0.1-rc.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upsidr/importer/releases/download/v0.0.1-rc.4/importer_0.0.1-rc.4_darwin_amd64.tar.gz"
      sha256 "364ee8f16af119410ee33284515ace883c8ffb167e4328514ccbe91f05157b55"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/upsidr/importer/releases/download/v0.0.1-rc.4/importer_0.0.1-rc.4_linux_amd64.tar.gz"
      sha256 "83222113d76cf98a97c657834c20776d0728b456f4e26311190649f2dc8c23c4"
    end
  end

  def install
    bin.install "importer"
  end
end
